parse_config:
  zmk_additional_includes: [ "zmk-helpers/include" ]
  modifier_fn_map:
    left_shift: ‚áß
    left_alt: ‚å•
    right_alt: Alt
    left_ctrl: ^
    left_gui: ‚åò
    keycode_combiner: "{mods}{key}"
    mod_combiner: "{mod_1}{mod_2}"
  raw_binding_map:
    "&bootloader": flash
    "&bt_sel 0": BT 1
    "&bt_sel 1": BT 2
    "&bt_sel 2": BT 3
    "&bt_sel 3": BT 4
    "&bt_sel 4": BT 5
    "&bt_clr 0": clear 1
    "&bt_clr 1": clear 2
    "&bt_clr 2": clear 3
    "&bt_clr 3": clear 4
    "&bt_clr 4": clear 5
    "&caps_word": caps word
    "&flash 6": dongle flash
    "&ind_bat": battery status
    "&ind_con": BT status
    "&kp BSPC": ‚å´
    "&kp DEL": ‚å¶
    "&kp ESC": Esc
    "&kp RET": ‚Üµ
    "&kp TAB": ‚á•
    "&kp UP": ‚Üë
    "&kp DOWN": ‚Üì
    "&kp LEFT": ‚Üê
    "&kp RIGHT": ‚Üí
    "&kp HOME": Home
    "&kp END": End
    "&kp PG_UP": PgUp
    "&kp PG_DN": PgDn
    "&kp GLOBE": üåê
    "&kp LALT": ‚å•
    "&kp RALT": Alt
    "&kp LCTL": ^
    "&kp LCTRL": ^
    "&kp LGUI": ‚åò
    "&kp LSFT": ‚áß
    "&kp LSHFT": ‚áß
    "&kp C_PP": ‚èØ
    "&kp C_PREV": ‚èÆ
    "&kp C_NEXT": ‚è≠
    "&kp SPC": ‚ê£
    "&kp CAPS": Caps üîí
    "&kp KP_NUM": Num üîí
    "&lp_mc": Launchpad MissionCtrl
    "&sk LSHIFT": sticky ‚áß
    "&studio_unlock": ZMK Studio
    "&usb_sel": USB
    "&tmsw N1": tmux 1
    "&tmsw N2": tmux 2
    "&tmsw N3": tmux 3
    "&tmsw N4": tmux 4
    "&tmsw N5": tmux 5
    "&tmsw N6": tmux 6
    "&tmsw N7": tmux 7
    "&tmsw N8": tmux 8
    "&tmsw N9": tmux 9
    "hu_a_acute": √Å
    "hu_e_acute": √â
    "hu_i_acute": √ç
    "hu_o_acute": √ì
    "hu_o_diaeresis": √ñ
    "hu_o_double_acute": ≈ê
    "hu_u_acute": √ö
    "hu_u_diaeresis": √ú
    "hu_u_double_acute": ≈∞
    GS(N4): screen shot
    GCS(N4): screen copy
    GC(Q): lock screen
